[project]
name = "tan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "javav12", email = "javav13@proton.me" }
]
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.22.3",
    "ruff>=0.16.9",
    "staticx>=0.14.2",
]

[project.scripts]
tan = "tan:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
