name: Build and Static Package

on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: Kodu Depodan Çek
              uses: actions/checkout@v4

            - name: Sistem Python ve Paket Yöneticisini Güncelle
              run: |
                  sudo apt-get update
                  sudo apt-get install -y patchelf binutils scons python3-pip python3-full python3-venv

            - name: Sanal Ortam Oluştur ve Araçları Yükle
              # Sistem python'ı üzerinden sanal ortam kurarak RUNPATH çakışmalarını engelliyoruz
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install --upgrade pip
                  pip install pyinstaller staticx

            - name: PyInstaller ile Tek Dosya Olarak Derle
              run: |
                  source venv/bin/activate
                  pyinstaller --onefile --clean script.py

            - name: StaticX ile Statik/Taşınabilir Hale Getir
              run: |
                  source venv/bin/activate
                  staticx dist/script dist/script_static

            - name: Çıktı Dosyasını Artifact Olarak Kaydet
              uses: actions/upload-artifact@v4
              with:
                  name: static-executable
                  path: dist/script_static
