name: Build and Static Package

on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: get code from repo
              uses: actions/checkout@v4

            - name: install Python env
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"

            - name: install some req
              run: |
                  sudo apt-get update
                  sudo apt-get install -y patchelf binutils scons

            - name: install Python req and tools
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller staticx

            - name: one file via pyinstaller
              run: |
                  pyinstaller --onefile --clean src/tan/tan_main.py

            - name: make it static via staticx
              run: |
                  staticx dist/tan_main dist/tan

            - name: upload output
              uses: actions/upload-artifact@v4
              with:
                  name: static-executable
                  path: dist/tan
