name: Build and Static Package

on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: get code from repo
              uses: actions/checkout@v4

            - name: install Python env and system tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y patchelf binutils scons python3-full python3-venv

            - name: install Python req and tools via venv
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  python -m pip install --upgrade pip
                  pip install pyinstaller staticx

            - name: one file via pyinstaller
              run: |
                  source venv/bin/activate
                  pyinstaller --onefile --clean src/tan/tan_main.py

            - name: make it static via staticx
              run: |
                  source venv/bin/activate
                  staticx dist/tan_main dist/tan

            - name: upload output
              uses: actions/upload-artifact@v4
              with:
                  name: static-executable
                  path: dist/tan
